import 'package:budget/colors.dart';
import 'package:budget/database/tables.dart';
import 'package:flutter/material.dart';

List<TransactionCategory> defaultCategories() {
  return [
    TransactionCategory(
      categoryPk: 1,
      name: "Food",
      colour: toHexString(Colors.blueGrey),
      iconName: "cutlery.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 0,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 2,
      name: "Groceries",
      colour: toHexString(Colors.green),
      iconName: "groceries.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 1,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 3,
      name: "Shopping",
      colour: toHexString(Colors.pink),
      iconName: "shopping.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 2,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 4,
      name: "Transit",
      colour: toHexString(Colors.yellow),
      iconName: "tram.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 3,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 5,
      name: "Entertainment",
      colour: toHexString(Colors.blue),
      iconName: "popcorn.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 4,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 6,
      name: "Bills & Fees",
      colour: toHexString(Colors.green),
      iconName: "bills.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 5,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 7,
      name: "Education",
      colour: toHexString(Colors.blue),
      iconName: "graduation.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 6,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 8,
      name: "Gifts",
      colour: toHexString(Colors.red),
      iconName: "gift.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 7,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 9,
      name: "Sports",
      colour: toHexString(Colors.cyan),
      iconName: "sports.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 8,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 10,
      name: "Beauty",
      colour: toHexString(Colors.purple),
      iconName: "flower.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 9,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 11,
      name: "Work",
      colour: toHexString(Colors.brown),
      iconName: "briefcase.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 10,
      income: false,
    ),
    TransactionCategory(
      categoryPk: 12,
      name: "Travel",
      colour: toHexString(Colors.orange),
      iconName: "plane.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 11,
      income: false,
    ),
  ];
}
