import 'package:flutter/material.dart';

String globalAppName = "Cashew";

Map<String, Locale> supportedLocales = {
  "en": Locale("en"),
  "fr": Locale("fr"),
  "es": Locale("es"),
  "zh": Locale("zh"),
  "zh_Hant": Locale.fromSubtags(languageCode: "zh", scriptCode: "Hant"),
  "hi": Locale("hi"),
  "ar": Locale("ar"),
  "pt": Locale("pt"),
  "ru": Locale("ru"),
  "ja": Locale("ja"),
  "de": Locale("de"),
  "ko": Locale("ko"),
  "tr": Locale("tr"),
  "it": Locale("it"),
  "vi": Locale("vi"),
  "pl": Locale("pl"),
  "nl": Locale("nl"),
  "th": Locale("th"),
  "cs": Locale("cs"),
  "bn": Locale("bn"),
  "da": Locale("da"),
  "fil": Locale("fil"),
  "fi": Locale("fi"),
  "el": Locale("el"),
  "gu": Locale("gu"),
  "he": Locale("he"),
  "hu": Locale("hu"),
  "id": Locale("id"),
  "ms": Locale("ms"),
  "ml": Locale("ml"),
  "mr": Locale("mr"),
  "no": Locale("no"),
  "fa": Locale("fa"),
  "ro": Locale("ro"),
  "sv": Locale("sv"),
  "ta": Locale("ta"),
  "te": Locale("te"),
  "uk": Locale("uk"),
  "ur": Locale("ur"),
  "sr": Locale("sr"),
  "sw": Locale("sw"),
  "bg": Locale("bg"),
};

// Language names can be found in 
// /budget/assets/static/language-names.json